data_dir: data
preprocess_data: false
goal: null
eval: null
log_dir: logs
workspace_dir: workspaces
copy_data: true
exp_name: run

exec:
  timeout: 3600
  agent_file_name: runfile.py
  format_tb_ipython: false

generate_report: true
report:
  model: qwen3.8-max
  temp: 1.0

experiment:
  num_syn_datasets: 1

debug:
  stage4: false

agent:
  type: parallel
  num_workers: 4
  stages:
    stage1_max_iters: 20
    stage2_max_iters: 12
    stage3_max_iters: 12
    stage4_max_iters: 18
  steps: 5
  k_fold_validation: 1
  multi_seed_eval:
    num_seeds: 3
  expose_prediction: false
  data_preview: false
  code:
    model: qwen3.8-max
    temp: 1.0
    max_tokens: 12000
  feedback:
    model: qwen3.8-max
    temp: 0.5
    max_tokens: 8192
  vlm_feedback:
    model: qwen3.8-max
    temp: 0.5
    max_tokens: null
  summary:
    model: qwen3.8-max
    temp: 0.3
  select_node:
    model: qwen3.8-max
    temp: 0.3
  search:
    max_debug_depth: 3
    debug_prob: 0.5
    num_drafts: 3
