#!/usr/bin/env python3
"""Complete a new scientific input view; existing generated bytes must match."""
import argparse,json,shutil
from pathlib import Path
from prepare_inputs import digest

def put(path,data):
    if path.exists():
        if path.is_symlink() or path.read_bytes()!=data:raise ValueError('existing generated input differs: '+str(path))
        return
    path.parent.mkdir(parents=True,exist_ok=True);path.write_bytes(data)

def finalize(dest):
    common=dest/'common';v1=dest/'ai-scientist-v1';here=Path(__file__).parent
    entry=common/'code/notebook/inference.py'
    original='os.environ["CUDA_HOME"] = os.environ["CONDA_PREFIX"]'
    portable='os.environ.setdefault("CUDA_HOME", os.environ.get("CONDA_PREFIX", "/opt/cuda"))'
    code=entry.read_text()
    if original in code:entry.write_text(code.replace(original,portable,1))
    elif portable not in code:raise ValueError('unrecognized inference environment setup')
    for src in sorted((common/'latex').rglob('*')):
        if src.is_symlink():raise ValueError('template link')
        if src.is_file():
            rel=src.relative_to(common/'latex');data=src.read_bytes()
            put(common/'native-latex'/rel,data);put(v1/'latex'/rel,data)
    for base in [common/'native-latex',v1/'latex']:
        put(base/'template.tex',(base/'main.tex').read_bytes())
    put(common/'code/run_frames.py',(here/'run_frames.py').read_bytes())
    put(v1/'experiment.py',(here/'artifacts/v1_experiment.py').read_bytes())
    put(v1/'plot.py',(here/'artifacts/v1_plot.py').read_bytes())
    put(v1/'seed_ideas.json',b'[]\n')
    rows=json.loads((common/'data/index.json').read_text())
    outputs=[{'frame_id':r['frame_id'],'splat':'/materials/baseline/'+r['frame_id']+'.ply'} for r in rows]
    put(v1/'run_0/final_info.json',(json.dumps({'baseline_outputs':outputs},indent=2)+'\n').encode())
    m=json.loads((dest/'operator-manifest.json').read_text())
    m['files']={str(p.relative_to(dest)):digest(p) for p in sorted(dest.rglob('*')) if p.is_file() and p.name!='operator-manifest.json'}
    m['status']='MATERIALIZED_CHECKPOINT_MOUNT_PENDING_RUNTIME_VALIDATION'
    (dest/'operator-manifest.json').write_text(json.dumps(m,indent=2)+'\n')
    return {'files':len(m['files']),'status':m['status']}
if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--dest',type=Path,required=True)
    print(json.dumps(finalize(p.parse_args().dest)))
